### ISSUE TITLE
Greek translation of title template, headings, labels

### ISSUE THREAD

**Issue by cicirello** [cicirello/user-statistician#148]
## Summary
Add Greek (`el`) translations of title template, headings, labels, etc for locale code `el`.

**Potential Contributors**
See [Contributing a Translation](https://github.com/cicirello/user-statistician#contributing-a-translation) section of the README for step-by-step instructions.

Please don't edit the README with the new locale code, despite the Pull Request template requesting that documentation is updated. Changes to the README automatically go live in the GitHub Marketplace listing for the action. I'll take care of updating README with the new locale code in the list of locales when I create the release that contains it to ensure that documentation is consistent with latest release.

**Comment by Sarthak027** [comment]
Iwant to work on this issue..

**Comment by Debasmita54** [comment]
Hey @cicirello  I want to contribute on this issue. Please assign this issue to me!!

**Comment by cicirello** [comment]
@Debasmita54 I just assigned you to it. Thanks for contributing.
