### ISSUE TITLE
Romanian translation of title template, headings, labels

### ISSUE THREAD

**Issue by cicirello** [cicirello/user-statistician#151]
## Summary
Add Romanian (`ro`) translations of title template, headings, labels, etc for locale code `ro`.

**Potential Contributors**
Only the [StatConfig.py](https://github.com/cicirello/user-statistician/blob/main/src/StatConfig.py) needs to be modified to implement this. Look for a comment block that has a list of steps necessary to contribute a locale. Start by creating a fork. Then create a branch in your fork for the new feature. Make your changes, and then submit a PR.

Please don't edit the README with the new locale code, despite the Pull Request template requesting that documentation is updated. Changes to the README automatically go live in the GitHub Marketplace listing for the action. I'll take care of updating README with the new locale code in the list of locales when I create the release that contains it to ensure that documentation is consistent with latest release.

**Comment by donheshanthaka** [comment]
Hey there, i would be happy to contribute to this project. can you assign me this issue?

**Comment by cicirello** [comment]
@donheshanthaka thanks for interest in contributing. I just assigned you to the issue.

**Comment by donheshanthaka** [comment]
Thank you very much.

**Comment by cicirello** [comment]
@donheshanthaka thank you for your contribution. I just merged your PR. It will probably be at least a week before I create a new release including your translation.

**Comment by donheshanthaka** [comment]
It's my pleasure :)
