### ISSUE TITLE
Persian translation of title template, headings, labels

### ISSUE THREAD

**Issue by cicirello** [cicirello/user-statistician#156]
**Summary**
Add Persian (`fa`) translations of title template, headings, labels, etc for locale code `fa`.

**Potential Contributors**
See [Contributing a Translation](https://github.com/cicirello/user-statistician#contributing-a-translation) section of the README for step-by-step instructions.

Please don't edit the README with the new locale code, despite the Pull Request template requesting that documentation is updated. Changes to the README automatically go live in the GitHub Marketplace listing for the action. I'll take care of updating README with the new locale code in the list of locales when I create the release that contains it to ensure that documentation is consistent with latest release.

**Comment by AshkanArabim** [comment]
Hey there! I speak Persian and I'd love to contribute to this repo.

**Comment by cicirello** [comment]
@AshkanArabim great. I just assigned you.
