### ISSUE TITLE
Finnish translation of title template, headings, labels

### ISSUE THREAD

**Issue by cicirello** [cicirello/user-statistician#160]
**Summary**
Add Finnish (`fi`) translations of title template, headings, labels, etc for locale code `fi`.

**Potential Contributors**
See [Contributing a Translation](https://github.com/cicirello/user-statistician#contributing-a-translation) section of the README for step-by-step instructions.

Please don't edit the README with the new locale code, despite the Pull Request template requesting that documentation is updated. Changes to the README automatically go live in the GitHub Marketplace listing for the action. I'll take care of updating README with the new locale code in the list of locales when I create the release that contains it to ensure that documentation is consistent with latest release.

**Comment by Sadeedpv** [comment]
Hey, I would love to work on this issue @cicirello

**Comment by cicirello** [comment]
Hi @Sadeedpv. Great. I just assigned you.

**Comment by Sadeedpv** [comment]
@cicirello I have created a PR
