### ISSUE TITLE
Feature Req: Refactor and standardize the code

### ISSUE THREAD

**Issue by alfawal** [cicirello/user-statistician#187]
**Is your feature request related to a problem? Please describe.**
The code is messy.
There is no specific formatter being used, redundant if statements everywhere and much more.

**Describe the solution you'd like**
- [x] Use Black formatter and isort to standardize the code.
- [ ] Add pre-commit to use flake8, black and isort.
- [ ] Use snake case naming instead of camel case.
- [x] Use absolute imports.
- [ ] Do small refactors.
- [ ] Move the big dictionaries to a separate file(s).

**Comment by cicirello** [comment]
Not interested in using the Black formatter. I dislike some of the formatting that it does, including some elements that come directly from the PEP 8 style guidelines (e.g., I like having a space before the `:` on first line of if statements and loops).

**Comment by alfawal** [comment]
it is up to you although this project won't have a noticeable contributions until it gets standardized in one way or another.
