### ISSUE TITLE
Fix GitHub themes to better match background

### ISSUE THREAD

**Issue by OMEGA6404** [cicirello/user-statistician#200]
Background color of dark theme doesn't match GitHub dark theme background.

**Comment by cicirello** [comment]
It has it: `colors: dark`.

**Comment by OMEGA6404** [comment]
yes, but the dark theme doesn't have the same color as gh dark theme

**Comment by cicirello** [comment]
@OMEGA6404 the theme's colors were derived directly from GH's dark theme. You can find the specifics in the comment that starts at this line: https://github.com/cicirello/user-statistician/blob/91df8408a837814b56c10ea3fee8a0bc92712522/src/Colors.py#L36  Do you have a suggestion for different color choices from the theme?

**Comment by cicirello** [comment]
@OMEGA6404 I changed the background of the various GitHub themes, including the dark theme, to use GitHub's canvas.default rather than canvas.inset. I believe this is likely what you were expecting of the background. Try release v1.20.2 to see the difference.

**Comment by OMEGA6404** [comment]
Thank you! sorry for being AFK lol
