### ISSUE TITLE
Hindi translation of title template, headings, labels

### ISSUE THREAD

**Issue by Viveksati5143** [cicirello/user-statistician#228]
# Summary

Add Hindi translations of title template, headings, labels, etc for locale code

**Comment by Viveksati5143** [comment]
Hey @cicirello👋
Is this a valid issue to work on under Hacktoberfest, If yes, can you please assign it to me?
Thanks.

**Comment by cicirello** [comment]
Hi @Viveksati5143 it would be a great issue to work on if it didn't already support Hindi. In fact, someone added Hindi 2 Hacktoberfests ago in #81. Thank you very much for interest in contributing though.

**Comment by Viveksati5143** [comment]
Thankyou @cicirello for confirming 
I can probably look for contribution in Swedish lang!?
