### ISSUE TITLE
Feature Req: Option to modify commit message

### ISSUE THREAD

**Issue by afuetterer** [cicirello/user-statistician#253]
**Is your feature request related to a problem? Please describe.**
Not really a problem. I would like to change the default commit message of the action (`Automated change by https://github.com/cicirello/user-statistician`) to a custom one.

**Describe the solution you'd like**
It would be nice to have an additional input to the action, e.g. `commit_message`, which could be provided by the user.

**Describe alternatives you've considered**
n.a.

**Additional context**
none

By the way: thanks for the wonderful action.

**Comment by cicirello** [comment]
@afuetterer Thanks for the suggestion. This was very easy to implement, and I had the time to do it. There is now a new input to customize the commit message, which you can now do with: `commit-message: Your custom commit message`. It is now available in `v1.23.0` or via the major release tag `v1`.

**Comment by afuetterer** [comment]
Excellent, thank you very much for the quick fix.

I will try the new version and input later today.

**Comment by afuetterer** [comment]
It works as expected, thanks again!

**Comment by cicirello** [comment]
@afuetterer You're welcome
