### ISSUE TITLE
Spanish language translation of headings, labels, etc.

### ISSUE THREAD

**Issue by cicirello** [cicirello/user-statistician#36]
**Summary**
Add Spanish translations of title template, headings, labels, etc for locale code es.

**Potential Contributors**
Only the [StatConfig.py](https://github.com/cicirello/user-statistician/blob/main/src/StatConfig.py) needs to be modified to implement this. Look for a comment block that has a list of steps necessary to contribute a locale. 

**Please target the dev branch with your PR.**

**Comment by alanverdugo** [comment]
Hi @cicirello , I can help with the Spanish translation. I am a native Spanish speaker, and you proyect looks interesting!
Could you please assign the issue to me?

**Comment by cicirello** [comment]
Hi @alanverdugo . Yes. Thank you.

**Comment by alanverdugo** [comment]
Thanks to you @cicirello ! Both for accepting the PR and for this project in general!
