### ISSUE TITLE
French language translations of title template, headings, labels, etc

### ISSUE THREAD

**Issue by cicirello** [cicirello/user-statistician#37]
**Summary**
Add French translations of title template, headings, labels, etc for locale code fr.

**Potential Contributors**
Only the [StatConfig.py](https://github.com/cicirello/user-statistician/blob/main/src/StatConfig.py) needs to be modified to implement this. Look for a comment block that has a list of steps necessary to contribute a locale. 

**Please target the dev branch with your PR.**

**Comment by thomasbnt** [comment]
Hello ! I can translate to french if you want @cicirello !

I see your GitHub Actions from [this post on DEV](https://dev.to/cicirello/hacktoberfest-participants-help-us-internationalize-the-user-statistician-github-action-2bga)

**Comment by cicirello** [comment]
Thanks @thomasbnt. That will be great.

**Comment by thomasbnt** [comment]
I start to contribute on October for **Hacktoberfest** event 💪🏼☕
