### ISSUE TITLE
Italian language translations of title template, headings, labels, etc

### ISSUE THREAD

**Issue by cicirello** [cicirello/user-statistician#39]
**Summary**
Add Italian translations of title template, headings, labels, etc for locale code it.

**Potential Contributors**
Only the [StatConfig.py](https://github.com/cicirello/user-statistician/blob/main/src/StatConfig.py) needs to be modified to implement this. Look for a comment block that has a list of steps necessary to contribute a locale. 

**Please target the dev branch with your PR.**

**Comment by ziriuz84** [comment]
I'm working on it
