### ISSUE TITLE
Portuguese language translation of title template, headings, labels, etc

### ISSUE THREAD

**Issue by cicirello** [cicirello/user-statistician#40]
**Summary**
Add Portuguese translations of title template, headings, labels, etc for locale code pt.

**Potential Contributors**
Only the [StatConfig.py](https://github.com/cicirello/user-statistician/blob/main/src/StatConfig.py) needs to be modified to implement this. Look for a comment block that has a list of steps necessary to contribute a locale. 

**Please target the dev branch with your PR.**

**Comment by andrefpoliveira** [comment]
Hey! Can I work on this? 😁

**Comment by cicirello** [comment]
@andrefpoliveira yes. That would be great.
