### ISSUE TITLE
Polish translation of title template, headings, labels

### ISSUE THREAD

**Issue by cicirello** [cicirello/user-statistician#74]
**Summary**
Add Polish translations of title template, headings, labels, etc for locale code pl.

**Potential Contributors**
Only the [StatConfig.py](https://github.com/cicirello/user-statistician/blob/main/src/StatConfig.py) needs to be modified to implement this. Look for a comment block that has a list of steps necessary to contribute a locale. 

**Please target the dev branch with your PR.**

**Comment by Jibendu007** [comment]
@cicirello  Can I be assigned to this?

**Comment by cicirello** [comment]
Hi @Jibendu007 yes. Thanks for interest in contributing.

**Comment by Jibendu007** [comment]
Thanks
