### ISSUE TITLE
Hindi translation of title template, headings, labels

### ISSUE THREAD

**Issue by cicirello** [cicirello/user-statistician#75]
**Summary**
Add Hindi translations of title template, headings, labels, etc for locale code hi.

**Potential Contributors**
Only the [StatConfig.py](https://github.com/cicirello/user-statistician/blob/main/src/StatConfig.py) needs to be modified to implement this. Look for a comment block that has a list of steps necessary to contribute a locale. 

**Please target the dev branch with your PR.**

**Comment by Anik-Bardhan** [comment]
@cicirello can I be assigned to this?

**Comment by cicirello** [comment]
@Anik-Bardhan Yes. That will be great.
