### ISSUE TITLE
Japanese translation of title template, headings, labels

### ISSUE THREAD

**Issue by cicirello** [cicirello/user-statistician#84]
**Summary**
Add Japanese translations of title template, headings, labels, etc for locale code ja.

**Potential Contributors**
Only the [StatConfig.py](src/StatConfig.py) needs to be modified to implement this. Look for a comment block that has a list of steps necessary to contribute a locale.

**Comment by a-ayush19** [comment]
@cicirello can you assign this to me?

**Comment by cicirello** [comment]
@a-ayush19 Yes.

**Comment by a-ayush19** [comment]
@cicirello kindly have a look at my pull request I just created, I've added the translations. Merge it if you feel fit.
Thank you.
