### ISSUE TITLE
 Swedish translation of title template, headings, labels

### ISSUE THREAD

**Issue by ponickkhan** [cicirello/user-statistician#94]
## Summary
Add Swedish (sv) translations of title template, headings, labels, etc for locale code sv.

**Potential Contributors**
See [Contributing a Translation](https://github.com/cicirello/user-statistician#contributing-a-translation) section of the README for step-by-step instructions.

Please don't edit the README with the new locale code, despite the Pull Request template requesting that documentation is updated. Changes to the README automatically go live in the GitHub Marketplace listing for the action. I'll take care of updating README with the new locale code in the list of locales when I create the release that contains it to ensure that documentation is consistent with latest release.

**Comment by ponickkhan** [comment]
can i work on this ?

**Comment by cicirello** [comment]
@ponickkhan yes.

**Comment by Viveksati5143** [comment]
I would like to work on this issue, Please assign it to me @cicirello

**Comment by cicirello** [comment]
@Viveksati5143 sounds great. I'll assign you now.
